### ISSUE TITLE
blank screen with command prompt instead of xdm when started by openrc

### ISSUE THREAD

**Issue by mrl5** [SELinuxProject/refpolicy#123]
this is a replication of:
- https://bugs.funtoo.org/browse/FL-6779
- https://bugs.gentoo.org/698112

**TL;DR**
when xdm is started by OpenRC it additionally wants to
```
type=AVC msg=audit(1571776002.581:399): avc: denied { chown } for pid=6225 comm="X" capability=0 scontext=system_u:system_r:xserver_t tcontext=system_u:system_r:xserver_t tclass=capability permissive=0
type=AVC msg=audit(1571776002.729:400): avc: denied { chown } for pid=6225 comm="X" capability=0 scontext=system_u:system_r:xserver_t tcontext=system_u:system_r:xserver_t tclass=capability permissive=0
```

this does not occur if this is run by root: `/etc/init.d/xdm start`

the bug is fixed when this is allowed: `allow xserver_t self:capability chown`

I don't know if this can be added to the global policy for xserver: 
https://github.com/SELinuxProject/refpolicy/blame/master/policy/modules/services/xserver.te#L636

**Comment by mrl5** [comment]
# X -version
X.Org X Server 1.20.5
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.19.67_p2-r1-debian-sources-lts x86_64 Gentoo
Current Operating System: Linux pc 4.19.67_p2-r1-debian-sources-lts #1 SMP Fri Sep 27 13:23:14 CEST 2019 x86_64
Kernel command line: BOOT_IMAGE=/kernel-debian-sources-lts-x86_64-4.19.67_p2-r1 real_root=/dev/sdc6 rootfstype=ext4 rand_id=FI38EHQ7 pci=nocrs security=selinux enforcing=1
Build Date: 11 October 2019  06:19:53P

# emerge -pv selinux-xserver openrc lightdm xdm
sec-policy/selinux-xserver-9999::security-kit
sys-apps/openrc-0.41.2-r1::core-kit  USE="bash-completion ncurses pam (selinux) unicode -audit -debug -netifrc -newnet (-prefix) -static-libs -zsh-completion"
x11-misc/lightdm-1.30.0::desktop-kit  USE="gnome gtk -audit -introspection -non_root -qt5 -vala"
x11-apps/xdm-1.1.11-r3::xorg-kit  USE="ipv6 pam -consolekit -xdm-auth"

**Comment by pebenito** [comment]
@perfinion

**Comment by mrl5** [comment]
... or perhaps it should be done as a boolean

**Comment by pebenito** [comment]
Closing stale issue. If this issue still remains, please work with the Gentoo maintainers and then they will upstream.
