### ISSUE TITLE
I have Suse linux 15.1. I want install refpolicy and selinux, but selinux-ready want program selinux-policy "check_packages: ERR. Package 'selinux-policy' not installed, please run 'zypper in selinux-policy' as root" I don`t have the oficial pakage. Haw I can run selinux? Help me please.

### ISSUE THREAD

**Issue by Olnes12** [SELinuxProject/refpolicy#126]

**Comment by fishilico** [comment]
Hello, I did not understand what you are asking. There seems to be a package named `selinux-policy` in https://software.opensuse.org/download.html?project=security%3ASELinux&package=selinux-policy. If there is an issue with the package-management software of your distribution, did you report it to your distribution's bug tracker? What answer did you receive there?
