### ISSUE TITLE
check_fc_files: support of '@' character

### ISSUE THREAD

**Issue by cgzones** [SELinuxProject/refpolicy#131]
Currently `check_fc_files` does not support the character `@` in file contexts, like

```
/usr/lib/systemd/system/getty@\.service --      gen_context(system_u:object_r:getty_unit_t,s0)
```

```
# ./testing/check_fc_files.py 
/root/workspace/selinux/selinux-policy-debian/policy/modules/system/getty.fc:8: unexpected characters @ in /usr/lib/systemd/system/getty@\.service
```

https://github.com/SELinuxProject/refpolicy/blob/0bfd1387acdde8e39e2bcfb4525285ad5e70e795/testing/check_fc_files.py#L155

@fishilico any reason not to support it?

**Comment by fishilico** [comment]
The reason why `@` was missing was only because there is currently no file context using it in refpolicy. As `@` is not a special symbol neither for `m4` nor `libpcre`, there would be no issue adding it in the regular expressions that look for invalid characters.
