### ISSUE TITLE
Hello! I configured the policy (refpolicy), included the type unconfined_t on the attribute mcs_constrained_type, but it still does not work (everyone has access to the files, even if they do not have that category.) What can be the reason? I will be very grateful for the advice.

### ISSUE THREAD

**Issue by Olnes12** [SELinuxProject/refpolicy#133]

**Comment by doverride** [comment]
On Sat, Nov 30, 2019 at 08:17:55AM -0800, Olnes12 wrote:

You would have to be a bit more specific than that.

Some information that may or may not help diagnose:

seinfo -xtunconfined_t
seinfo -xuunconfined_u
id -Z
ls -alZ "path to mcs file"

> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/133

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes12** [comment]
I thank you for your attention to my question. Your commands have helped me recheck my system. And o miraculously, everything worked.
