### ISSUE TITLE
user_u

### ISSUE THREAD

**Issue by Olnes12** [SELinuxProject/refpolicy#139]
Good day. I want to turn to society with this problem: I have Suse linux desktop 15.1. I configured SELinux refpolicy  standard without UBAC, but I can’t log in user_u.
I did audit2allow several times, then I opened boolean, then I opened all the locks through “ausearch  – m avc| grep permissive=0” and “semanage permissive –a system_tmpfiles_t”. 
At the moment, no locks through any shows. But when I turn on “setenforce 1” by root (sysadmin_r), I log out and when I try to log into the user (user_u), the screen locks and no errors are displayed. Please help in which direction to move. What is the error search technique?

**Comment by doverride** [comment]
On Tue, Dec 17, 2019 at 03:00:05AM -0800, Olnes12 wrote:
> Good day. I want to turn to society with this problem: I have Suse linux desktop 15.1. I configured SELinux refpolicy  standard without UBAC, but I can’t log in user_u.
> I did audit2allow several times, then I opened boolean, then I opened all the locks through “ausearch  – m avc| grep permissive=0” and “semanage permissive –a system_tmpfiles_t”. 
> At the moment, no locks through any shows. But when I turn on “setenforce 1” by root (sysadmin_r), I log out and when I try to log into the user (user_u), the screen locks and no errors are displayed. Please help in which direction to move. What is the error search technique?

Standard procedure is to make SELinux verbose with semodule -DB, then reproduce and look for avc denials. Use semodule -B to make SELinux silent again.

Besides above theres a few consideration:

1. Youre using "-m avc", this will not show all possibly relevant SELinux events. use '-m avc,user_avc,selinux_err -i' instead.
2. not all selinux events are always logged to audit (although most is) also check your other logs for selinux denials (grep -i denied)
3. There may or may not be pam (pam_selinux) related issues. You can make pam_selinux verbose (see man pam_selinux)

> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/139

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes12** [comment]
Thanks for the advice! Unfortunately, I was not able to achieve my goal. Have you ever encountered a situation where you go under user_u and the system itself changes selinux user to system_u?

**Comment by doverride** [comment]
On Fri, Dec 20, 2019 at 02:26:50AM -0800, Olnes12 wrote:
> Thanks for the advice! Unfortunately, I was not able to achieve my goal. Have you ever encountered a situation where you go under user_u and the system itself changes selinux user to system_u?

Yes, that usually indicates that there is a pam_selinux configuration issue.

I would need more information to be more helpful:

1. seinfo -xuuser_u
2. cat /etc/selinux/*/contexts/users/user_u
3. what program do you use to log in? show me a `ps auxZ | grep login program process`
4. when you log in as user_u in permissive mode then what context do you end up in `id -Z`
5. some general info about your policy `sestatus -vvv`
6. what kernel `uname -a`, what user space `rpm -qa | grep libselinux`

Answers to the above should be a start to get to the bottom of this

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/139#issuecomment-567875650

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes12** [comment]
file "selinux.docx"
  selinux file
 I can’t determine exactly which process I’m hanging in the file "gdm.docx" ps auxZ driver without grep, I think gdm-session-worker [pam / gdm-password] with the context system_u: system_r: xdm_t
 4.when enf 0 is user_u user_t ,5. in the selinux file, 6. in the selinux file
I would be grateful for any help.
[selinux.docx](https://github.com/SELinuxProject/refpolicy/files/3988313/selinux.docx)
[gdm.docx](https://github.com/SELinuxProject/refpolicy/files/3988324/gdm.docx)

**Comment by doverride** [comment]
On Fri, Dec 20, 2019 at 04:59:51AM -0800, Olnes12 wrote:
>   file "selinux.docx"
>   selinux file
>  I can’t determine exactly which process I’m hanging in the file "gdm.docx" ps auxZ driver without grep, I think gdm-session-worker [pam / gdm-password] with the context system_u: system_r: xdm_t
>  4.when enf 0 is user_u user_t ,5. in the selinux file, 6. in the selinux file
> I would be grateful for any help.
> [selinux.docx](https://github.com/SELinuxProject/refpolicy/files/3988313/selinux.docx)
> [gdm.docx](https://github.com/SELinuxProject/refpolicy/files/3988324/gdm.docx)

I don't do "docx"

But seems like youre just missing a permission.

Theres a simple guideline that say's that if it works in permissive mode but not in enforcing mode then selinux is blocking something.
If selinux is blocking then, generally, it will log the event its blocking.
If selinux is blocking but not logging the event then you would run semodule -DB to make selinux verbose, reproduce the issue and look again for selinux event logs. (run semodule -B to make selinux quiet again)

Make sure that you look for all selinux event types (ausearch -m avc,user_avc,selinux_err -i -ts ...)
Make sure that you  also look elsewhere for selinux denials (journalctl -rb --grep denied, dmesg | grep -i denied)

> 
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/139#issuecomment-567916504

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes12** [comment]
[gdm.pdf](https://github.com/SELinuxProject/refpolicy/files/3988508/gdm.pdf)
[selinux.pdf](https://github.com/SELinuxProject/refpolicy/files/3988509/selinux.pdf)
semodule -DB included, but the question is why audit2allow -a does not see locks?

**Comment by doverride** [comment]
On Fri, Dec 20, 2019 at 05:50:42AM -0800, Olnes12 wrote:
> [gdm.pdf](https://github.com/SELinuxProject/refpolicy/files/3988508/gdm.pdf)
> [selinux.pdf](https://github.com/SELinuxProject/refpolicy/files/3988509/selinux.pdf)
> semodule -DB included, but the question is why audit2allow -a does not see locks?

Not sure why `audit2allow -a` wouldnt work for you but alternatively just pipe the avc denials into audit2allow stdin:

ausearch -m avc,user_avc,selinux_err -ts today | audit2allow
journalctl -rb --grep denied | audit2allow

Everything looks good to me but there except for one issue that is not addressed/supported in the policy where systemd spawns a systemd --user instance for gdm with the wrong context (effectively breaking gdm).

1. does it work in permissive mode?
2. if the answer to 1 is yes then selinux is blocking and there should be avc denials of the event its blocking. You can pipe those avc denials into audit2allow to allow it.

alternatively you can try the unconfined "unconfined_u" selinux user instead of the confined "user_u" selinux user.
confined users (user_u) in a gnome environment is not very actively supported currently AFAIK.

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/139#issuecomment-567931059

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes** [comment]
Happy New Year. After careful work by the audit, everything worked out, thanks  doverride. There was one problem when I go under user_u with programs XTERM and enter id -Z, then I see contex  system_u system_r xdm_t   It is weird, 
because through the program Terminal context user_u user_r user_t

**Comment by doverride** [comment]
On Sat, Jan 11, 2020 at 03:54:28AM -0800, Olnes wrote:
> Happy New Year. After careful work by the audit, everything worked out, thanks  doverride. There was one problem when I go under user_u with programs XTERM and enter id -Z, then I see contex  system_u system_r xdm_t   It is weird, 
> because through the program Terminal context user_u user_r user_t

That sounds like a potential security risk. Not sure whether that is mis configuration or a bug in policy.

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/139#issuecomment-573310184

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes** [comment]
Interestingly, I looked and saw that even a fresh system, without any changes on my part (audit2allow, modules), immediately shows the context in the XTERM system_u system_r xdm_t application, and much can be done from it. How to ban it? I also see that many other processes work under a different context (not user_r).

**Comment by doverride** [comment]
On Mon, Jan 13, 2020 at 01:26:58AM -0800, Olnes wrote:
> Interestingly, I looked and saw that even a fresh system, without any changes on my part (audit2allow, modules), immediately shows the context in the XTERM system_u system_r xdm_t application, and much can be done from it. How to ban it? I also see that many other processes work under a different context (not user_r).

Hard to say without (much) more information.

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/139#issuecomment-573574183

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by Olnes** [comment]
Good day.What data is needed? I am ready to provide them. I noticed that xterm is started by the bin / xterm file, for example, the terminal from usr / bin / gnome-terminal, but the context of their files is the same system_u object_r bin_t. The  ps -efZ | grep xterm command shows xdm_t root 3468 3037 tty2 (from root, 3468 is bash).

**Comment by doverride** [comment]
Olnes <notifications@github.com> writes:

> Good day.What data is needed? I am ready to provide them. I noticed that xterm is started by the bin / xterm file, for example, the terminal
> from usr / bin / gnome-terminal, but the context of their files is the same system_u object_r bin_t. The ps -efZ | grep xterm command shows
> xdm_t root 3468 3037 tty2 (from root, 3468 is bash).

Not sure exactly what data i would need to get to the bottom of this but
this might be a start:

1. how is xterm started exactly?
2. excluse a `ps auxZ` with xterm running
3. ls -alZ `whereis xterm`

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift

**Comment by doverride** [comment]
Dominick Grift <dac.override@gmail.com> writes:

> Olnes <notifications@github.com> writes:
>
>> Good day.What data is needed? I am ready to provide them. I noticed that xterm is started by the bin / xterm file, for example, the terminal
>> from usr / bin / gnome-terminal, but the context of their files is the same system_u object_r bin_t. The ps -efZ | grep xterm command shows
>> xdm_t root 3468 3037 tty2 (from root, 3468 is bash).
>
> Not sure exactly what data i would need to get to the bottom of this but
> this might be a start:
>
> 1. how is xterm started exactly?
> 2. excluse a `ps auxZ` with xterm running

I mean "enclose"

Also probably more productive if you take this to IRC
(irc://irc.freenode.org/selinux)

I go by "grift" there

> 3. ls -alZ `whereis xterm`
>
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>

-- 
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift
