### ISSUE TITLE
Reporting a security issue

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#150]
Who do I report a security vulnerability in the reference policy to?

**Comment by fishilico** [comment]
Hello,
I am not aware of a clear process to handle security vulnerabilities for this project. Anyway, if fixing the vulnerability you found requires publishing a new release of the policy, the only person who perform releases is @pebenito, so you should contact him.

If you want help with reviewing patches, many people who review patches here have GPG keys and it should be possible to make such a review possible in a nice way.

If you want help handling the vulnerability (for example if the vulnerability is very urgent/causes immediate risk/etc.), it is possible to contact the security team of distribution(s) to speed things up. As far as I know, the reference policy is officially used on RHEL, Gentoo Hardened and Debian. Other distributions also provides packages or have people contribute packages to them (for example I provide packages to Arch Linux, using the Arch Linux User Repository).

By the way, in case you did not already know, Fedora does not directly use refpolicy, but uses a fork with many differences (https://github.com/fedora-selinux/selinux-policy). Therefore if the vulnerability you found also affects Fedora's policy, you might want to notify the security team of this distribution on their issue tracker.

Thanks

**Comment by pebenito** [comment]
Please contact me directly and we can discuss.
