### ISSUE TITLE
Access to udev "database"

### ISSUE THREAD

**Issue by bigon** [SELinuxProject/refpolicy#221]
Hello,

The udev module still references the `udev_tbl_t` as being stored in `/dev`, but these days, it's located in `/run`. That prevents some applications (like pcscd) to work properly.

Red Hat went the way of removing the `udev_tbl_t` type completely, see https://github.com/fedora-selinux/selinux-policy/commit/382acd84f3

Would that be the road to go as well?

**Comment by pebenito** [comment]
Sounds like it is the right choice.
