### ISSUE TITLE
Typos in init.te

### ISSUE THREAD

**Issue by bauen1** [SELinuxProject/refpolicy#270]
There are multiple statements refering to `initrc_t` in the `init_systemd` block that only handles `init_t`, are these meant to be for `init_t` or should they be moved to the `initrc_t` section ?

https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/system/init.te#L327

https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/system/init.te#L334

https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/system/init.te#L373

**Comment by pebenito** [comment]
Probably should be moved to the `initrc_t` section unless you can tell from the commit messages that they are typos.

**Comment by pebenito** [comment]
The all appear to be addressed..
