### ISSUE TITLE
Many daemons do not need to write user crontabs

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#280]
Being able to write user crontabs is enough to execute code as that user.

**Comment by bauen1** [comment]
Could you share an example ?
All the daemons that I see that can access `/var/spool/cron` (`cron_spool_t`) are daemons that have unconfined file access (due to being a package manager, ftpd or similiar)

**Comment by DemiMarie** [comment]
`/var/spool/cron` is `user_cron_spool_t` on my system, and all daemons have access to it.

**Comment by bauen1** [comment]
> `/var/spool/cron` is `user_cron_spool_t` on my system, and all daemons have access to it.

On my system `/var/spool/cron` is labeled as `cron_spool_t` as it should be:
```bash
$ matchpathcon /var/spool/cron
/var/spool/cron system_u:object_r:cron_spool_t:SystemLow
$ ls -alZd /var/spool/cron
drwxr-xr-x. 3 root root system_u:object_r:cron_spool_t:SystemLow 4096 Jul 16  2019 /var/spool/cron
```
Perhaps it became mislabeled on your system for some reason (e.g. turning off enforcing mode)
