### ISSUE TITLE
ipsec_mgmt_t needs to be able to drop privileges

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#281]
StrongSwan supports switching users after startup.  However, SELinux currently blocks this, as `ipsec_mgmt_t` is not allowed `CAP_SETUID` or `CAP_SETGID`.

Of course, running StrongSwan as an unprivileged user (with capabilities) would be preferable, but isn’t supported well.

**Comment by DemiMarie** [comment]
This should probably be guarded by a boolean, so that it can easily be turned off once StrongSwan doesn’t need to start as root.

**Comment by pebenito** [comment]
If this is still valid, I would need some help since I don't have an IPSEC setup.

**Comment by DemiMarie** [comment]
It isn’t.  The real problem was wrong labels on `/usr/sbin/strongswan`.
