### ISSUE TITLE
Most daemons should not be allowed to write to /tmp

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#282]
Writing to `/tmp` is often enough to execute code as the UID the daemon is running as, often root.  This can bypass SELinux restrictions.

**Comment by pebenito** [comment]
Each domain should have its own private type in /tmp so there shouldn't be interference between daemons. Worst case is DoS where there is a collision between two domains trying to write the same file. These days, this concern can be mitigated with systemd PrivateTmp option.

If there are specific cases where this doesn't hold, please feel free to reropen.

**Comment by bauen1** [comment]
> Each domain should have its own private type in /tmp so there shouldn't be interference between daemons. Worst case is DoS where there is a collision between two domains trying to write the same file. These days, this concern can be mitigated with systemd PrivateTmp option.

So only the directory `/tmp` should be labeled as `tmp_t` ?

On my fork of refpolicy (similliar enough) systemd (`init_t`) will create directories under `/tmp` with the `tmp_t` label, e.g.
`drwx------.  3 root root system_u:object_r:tmp_t:SystemLow                60 Aug 19 12:33 systemd-private-cf7d0255a59c4e91bc6b2646021d2c66-systemd-timesyncd.service-ywGvSf`
However I'm also not sure how useful it is the add a separate type for these.
Of course all domains that are a part of `files_unconfined` can do this of course too, especially if lacking proper types and type transitions, but that probably isn't a concern.

**Comment by pebenito** [comment]
If I'm not mistaken, those `systemd-private-*` dirs become the `/tmp` of the `PrivateTmp` namespaces, so they need to be `tmp_t`. Otherwise, yes, `tmp_t` should typically be only the top level dir label. All bets are off for anything that is unconfined.

**Comment by bauen1** [comment]
> If I'm not mistaken, those `systemd-private-*` dirs become the `/tmp` of the `PrivateTmp` namespaces, so they need to be `tmp_t`. Otherwise, yes, `tmp_t` should typically be only the top level dir label.

I think systemd will present the directory to the process with the same label as `/tmp` has.
So with my CIL policy `/tmp` is labeled `tmp.type` but `/tmp/systemd-private-*` has the label `init.tmp.type`.
I've so far had no issue with this but YMMV.

> All bets are off for anything that is unconfined.

Of course.
On that note, removing or updating some of the very old modules (`anaconda` and `mono`) that are part of this attribute is probably a good idea.
