### ISSUE TITLE
Update CPE

### ISSUE THREAD

**Issue by aparcar** [SELinuxProject/refpolicy#306]
The current `refpolicy` CPE still points to `tresys`, however this project moved over to `selinuxproject`. Please add an updated entry to [nvm.nist.gov](https://nvd.nist.gov/products/cpe/search/results?keyword=refpolicy).

**Comment by pebenito** [comment]
Sent a request to NIST.

**Comment by pebenito** [comment]
The NVD should be updated in the next 24hr.

**Comment by pebenito** [comment]
new CPE: cpe:2.3:a:selinuxproject:refpolicy:*:*:*:*:*:*:*:*
