### ISSUE TITLE
PR checks are broken

### ISSUE THREAD

**Issue by galaxy4public** [SELinuxProject/refpolicy#316]
It seems that this repository underwent a reconfiguration for the Travis checks and now there are two CI checks defined.  Both are Travis CI, but one (the newer) is working while the other one (the older) does not.  Should the `continuous-integration/travis-ci` check be decommissioned?

**Comment by pebenito** [comment]
There was a change in Travis CI service and the migration didn't remove the old check. It's fixed now.
