### ISSUE TITLE
Confined user dbus instances cannot activate services

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#329]
This is due to missing `service start` rules.

**Comment by DemiMarie** [comment]
Here is the patch I used for my own policy:

```diff
diff --git a/qubes.fc b/qubes.fc
index ab251f1..adb479b 100644
--- a/qubes.fc
+++ b/qubes.fc
@@ -23,3 +23,14 @@
 `/rw/config/firewall\.nft'		gen_context(system_u:object_r:etc_t,s0)
 `/rw/config/tinyproxy'		-d	gen_context(system_u:object_r:etc_t,s0)
 `/rw/config/tinyproxy/[^/]+'	--	gen_context(system_u:object_r:tinyproxy_config_t,s0)
+`/run/user/[^/]+/systemd'	-d	gen_context(`system_u:object_r:init_var_run_t',`s0')
+`/run/user/[^/]+/systemd/generator(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/run/user/[^/]+/systemd/generator\.early(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/run/user/[^/]+/systemd/generator\.late(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/run/user/[^/]+/systemd/user(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/var/run/user/[^/]+/systemd'	-d	gen_context(`system_u:object_r:init_var_run_t',`s0')
+`/var/run/user/[^/]+/systemd/generator(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/var/run/user/[^/]+/systemd/generator\.early(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/var/run/user/[^/]+/systemd/generator\.late(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/var/run/user/[^/]+/systemd/user(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
+`/var/run/user/[^/]+/systemd/transient(/.*)?'	gen_context(`system_u:object_r:systemd_unit_file_t',`s0')
diff --git a/qubes.te b/qubes.te
index 785401e..835e3db 100644
--- a/qubes.te
+++ b/qubes.te
@@ -13,14 +13,14 @@ gen_require(``
 	type sysadm_t, sysadm_dbusd_t, sysadm_sudo_t;
 	type semanage_t, user_home_t, admin_home_t, load_policy_t;
 	type su_exec_t, sulogin_t, sysfs_t;
-	type systemd_logind_t, systemd_modules_load_t, systemd_unit_file_t, tmp_t, tmpfs_t;
+	type systemd_logind_t, systemd_modules_load_t, systemd_unit_file_t, systemd_runtime_unit_file_t, tmp_t, tmpfs_t;
 	type systemd_resolved_t;
 	type tty_device_t, tracefs_t, udev_t, unlabeled_t;
 	type utempter_t;
 	type user_tmp_t, user_devpts_t, unconfined_t, var_log_t, virsh_exec_t;
 	type xend_t, xenfs_t, setfiles_t;
 	type xauth_exec_t, xdm_t, xen_device_t;
-	type xend_var_log_t, xdm_home_t;
+	type xend_var_log_t, xdm_home_t, xdm_unit_file_t;
 	class file entrypoint;
 	class passwd rootok;
 	class system module_load;
@@ -31,7 +31,7 @@ gen_require(``
 	class chr_file { getattr open read write };
 	class dbus { send_msg };
 	class process2 nnp_transition;
-	attribute userdomain, admindomain, staff_usertype, sysadm_usertype;
+	attribute userdomain, admindomain, staff_usertype, sysadm_usertype, systemd_unit_file_type;
 	role staff_r, sysadm_r;
 '')`
 
@@ -273,7 +273,12 @@ typeattribute NetworkManager_t qubesdb_access;
 dontaudit utempter_t user_tmp_t:fifo_file write;
 
 #============= staff_dbus_t ==============
-allow staff_dbusd_t systemd_unit_file_t:service start;
+allow staff_dbusd_t systemd_unit_file_type:service start;
+# typeattribute user_tmp_t systemd_unit_file_type;
+type_transition domain init_var_run_t:dir systemd_unit_file_t "generator.early";
+type_transition domain init_var_run_t:dir systemd_unit_file_t "generator.late";
+type_transition domain init_var_run_t:dir systemd_runtime_unit_file_t "transient";
+type_transition userdomain user_tmp_t:dir init_var_run_t "systemd";
 
 # Allow initrc_domains to transition to anything with NoNewPrivileges=yes
 allow initrc_domain domain:process2 nnp_transition;
diff --git a/qubes_selinux.spec b/qubes_selinux.spec
index 84d2565..ff36133 100644
```

**Comment by pebenito** [comment]
There are separate domains for `systemd --user` instances, but it is rudimentary and still needs more work. We will need to add a new type for the user instance units, pull in the file contexts and dbus service rule.

**Comment by doverride** [comment]
I think it should be noted that there is a fundamental difference between dbus activation with dbus-daemon and dbus-broker where dbus-broker activates the daemon via systemd and where dbus-daemon activates the daemon by running it it self.

Another difference between dbus-daemon and dbus-broker is that dbus-daemon performs access checks on "method_return" and "dbus-broker" does not.

The thing with dbus-broker activation is that if there is no unit available for a given dbus activated daemon, then dbus-broker uses a runtime unit. If you allow that then dbus-broker can essentially escalate to initrc_t.

**Comment by DemiMarie** [comment]
`dbus-broker` (and `dbus-daemon`) are both considered trusted.  They have complete control of systemd over D-Bus, so they can escalate privileges to anything that allows.  That is almost always unconfined root.

That said, we might not want `dbus-broker` to start runtime units itself creates.  `dbus-broker` will use its own credentials there, which might help.  One could argue that not having a unit available for a dbus activated daemon is a packaging bug, in which case a failure is normal.

**Comment by pebenito** [comment]
> That said, we might not want `dbus-broker` to start runtime units itself creates. `dbus-broker` will use its own credentials there, which might help. One could argue that not having a unit available for a dbus activated daemon is a packaging bug, in which case a failure is normal.

I agree, though in terms of refpolicy I don't think it could be unconditionally denied (i.e. use a tunable).

**Comment by 0xC0ncord** [comment]
I'd like to take a stab at this but I need a few things clarified:

> I think it should be noted that there is a fundamental difference between dbus activation with dbus-daemon and dbus-broker where dbus-broker activates the daemon via systemd and where dbus-daemon activates the daemon by running it it self.

What does this transition look like? I've never used `dbus-broker` before. My understanding is that, for example, `staff_dbusd_t` will execute some `bin_t` and transition to `staff_t` when `dbus-daemon` is being used. My interpretation from the above is that when using `dbus-broker`, the systemd user instance labeled `staff_systemd_t` will run the unit and transition to `staff_t` that way. Is this correct?

> The thing with dbus-broker activation is that if there is no unit available for a given dbus activated daemon, then dbus-broker uses a runtime unit. If you allow that then dbus-broker can essentially escalate to initrc_t.

The proper mitigation for this should be a tunable that grants dbus domains to run runtime units, and it should ideally be enabled when `dbus-daemon` is used. Correct? My main concern with this is what should be the default? Most systems seem to be running `dbus-daemon`, so that points to this permission being enabled by default so that things work out of the box, but this means that systems running `dbus-broker` will have this potential escalation weakness allowed by default as well.

In my opinion the best way to handle all of this would be to modify the template for systemd user instances to create the corresponding user units as well, or use constraints to enforce separation between user units. That being said, I'm not sure if that strict separation is entirely necessary. Any thoughts?

**Comment by 0xC0ncord** [comment]
Thanks for the insight. I will whip up something locally and see if I can produce a working policy for this, but I don't think I'll be able to test with `dbus-broker` on my systems. Expect a PR marked WIP soon.
