### ISSUE TITLE
Create a custom tag

### ISSUE THREAD

**Issue by BigTree975** [SELinuxProject/refpolicy#345]
I follow the wiki tutorial to create a custom tag, but the last tag used by the nginx process is init_t. Can you give me some advice

[nginx.zip](https://github.com/SELinuxProject/refpolicy/files/5892251/nginx.zip)

**Comment by doverride** [comment]
That file is unreadable. There is some interactive community support on irc://chat.freenode.net/selinux

**Comment by BigTree975** [comment]
[nginx.zip](https://github.com/SELinuxProject/refpolicy/files/5893748/nginx.zip)
Change the file format to txt, I'm installing Nginx from source code and I want to create custom tags for it with as few tags as possible

**Comment by doverride** [comment]
it is unreadable....

```
[kcinimod@brutus Downloads]$ cat __MAC*/._nginx_fc.txt
Mac OS X        	2ATTR$$com.apple.TextEncoding3com.apple.lastuseddate#PSCHcom.apple.maclY7com.apple.metadata:kMDLabel_gq7h5knoovvlajwwdrgtby56byutf-8;134217984`c,v}M
1z!h=vSy'RD'TZ@a Y5%di;Rt_\a	[kcinimod@brutus Downloads]$      Cj[7όH}7clt'ȡj?֛
```

**Comment by doverride** [comment]
o never mind i think i figured it out ...

add this to nginx.te:

```
init_daemon_domain(nginx_t, nginx_exec_t)
role system_r types nginx_t;
```

**Comment by BigTree975** [comment]
This should be OK😥

[nginx_fc.txt](https://github.com/SELinuxProject/refpolicy/files/5893859/nginx_fc.txt)
[nginx_te.txt](https://github.com/SELinuxProject/refpolicy/files/5893860/nginx_te.txt)
[nginx_if.txt](https://github.com/SELinuxProject/refpolicy/files/5893861/nginx_if.txt)
[chcon_sh.txt](https://github.com/SELinuxProject/refpolicy/files/5893864/chcon_sh.txt)

**Comment by doverride** [comment]
yes I managed to read it... See solutiion above

**Comment by doverride** [comment]
You might even be able to omit the `role system_r types nginx_t;` line as its probably implied with `init_daemon_domain(nginx_t, nginx_exec_t)` line

**Comment by BigTree975** [comment]
This allows me to configure the ‘allow’ policy according to the AVC of the audit.log, and to configure the new tag for nginx and access it successfully. 
Thank you very much!

**Comment by BigTree975** [comment]
I want to specify some ports for my nginx process , but the configuration of nginx_port_t doesn't seem to work. How do I configure the port label belonging to nginx

**Comment by doverride** [comment]
Suleo Wang <notifications@github.com> writes:

> I want to specify some ports for my nginx process , but the configuration of nginx_port_t doesn't seem
> to work. How do I configure the port label belonging to nginx

Not sure what you mean but try this:

cat > mytest.te <<EOF
policy_module(mytest,1.0,0)
type nginx_port_t;
corenet_port(nginx_port_t)
EOF
make -f /usr/share/selinux/devel/Makefile mytest.pp
sudo semodule -i mytest.pp
sudo semanage port -a -t nginx_port_t -p tcp 5555
sudo seinfo --portcon | grep nginx

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
gpg --locate-keys dominick.grift@defensec.nl
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift

**Comment by BigTree975** [comment]
Yes, I am missing `corenet_port(nginx_port_t)`. Where can I find the complete documentation for the custom SELinux tag?Writing SELinux tags as a novice is difficult!

**Comment by doverride** [comment]
Suleo Wang <notifications@github.com> writes:

> Yes, I am missing corenet_port(nginx_port_t). Where can I find the complete documentation for the
> custom SELinux tag?Writing SELinux tags as a novice is difficult!

The reference policy makefile has a "make docs" build target which will
create "interface reference" html that can be used to peruse the API.

Eventually though the challenge of interpretting selinux policy is not reference
policy specific. One should ideally be able to interpret any selinux policy and
this requires two things:

1. one should know the SELinux policy language (the language is
documented here: https://github.com/SELinuxProject/selinux-notebook)

2. one should know how to use the setools policy analysis suite to get
answer to any selinux policy specific questions (the setools suite is
ther https://github.com/SELinuxProject/setools)

Once you can interpret the selinux policy language and once you are
familiar with setools you will be able to use those skills to find answers to any questions
related to any given selinux policy.


>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 
gpg --locate-keys dominick.grift@defensec.nl
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
https://sks-keyservers.net/pks/lookup?op=get&search=0xDA7E521F10F64098
Dominick Grift
