### ISSUE TITLE
kmod_t and udev_t cannot use tracefs with kernel_lockdown

### ISSUE THREAD

**Issue by MicaOliver1810** [SELinuxProject/refpolicy#352]
Hi, I'm encountering errors in the lockdown subsystem where kmod_t and udev_t forbid the use of tracefs. I've been able to skate without rules allowing confidentiality for these types up until last kernel update (Arch hardened x64, 5.10.12) at which point I'm seeing log errors that look like this:

```
AVC avc: denied {confidentiality} for pid=325 comm=systemd-udevd lockdown reason="use of tracefs" scontext=system_u:system_r:udev_t tcontext=system_u:system_r:udev_t tclass=lockdown permissive=0

Could not create tracefs "filter" entry Could not create tracefs "id" entry Could not create tracefs "enable" entry 
```

These are showing up practically thousands of times and making it impossible to read the log when it's needed to diagnose problems (after kernel or application panic for instance). Masking tracefs, which one would think prevents it from loading thereby attempts made to use it, doesn't help.  If this is the way it is for a reason, can someone please enlighten me as to why, and if not is there anything that can be done?

**Comment by doverride** [comment]
There is a patch pending that addresses this issue. In the meantime you could use `audit2allow` to allow the access.

**Comment by pebenito** [comment]
@MicaOliver1810 is the lockdown reason also "use of tracefs" for `kmod_t`?
