### ISSUE TITLE
Reference policy gives following error when trying to get audit denial logs and modules load time 

### ISSUE THREAD

**Issue by rammohanreddy434** [SELinuxProject/refpolicy#36]
Hi, 
I have taken reference policy and compiled, but it gives the  following error 
   ` ** Libsepol. context_from_record: MLS is disabled, but MLS context "s0" found  `\
       ` Libsepol. context_from_record: could not create context structure**`
This error when trying to get denial logs using ` **audit2allow -a -w**` and modules load time. Here I'm using the reference policy old version with required dependency packages and I tried all versions of the reference policy with a required dependence version of packages but I'm not succeeding. 

Thanks in advance,

**Comment by pebenito** [comment]
Is MLS disabled in your policy? This seems like an audit2allow problem, not a refpolicy problem.

**Comment by rammohanreddy434** [comment]
HI pebenito,
* if  enable `MLS`  in build.conf and compile ,then audit2allow -a -w gives the following error...
`ibsepol.sepol_context_to_sid: could not convert system_u:system_r:systemd_cgroups_t:s0 to sid
libsepol.context_from_record: type systemd_logind_t is not defined
libsepol.context_from_record: could not create context structure` 
* If generate policy  using audit2allow 
`#!!!! This avc is a constraint violation.  You would need to modify the attributes of either the source or target types to allow this access.
#Constraint rule: 
        mlsconstrain dir { create } ((l1 eq l2 -Fail-)  or (t1 == mlsfileupgrade -Fail-)  and (l1 domby l2 -Fail-)  or (t1 == mlsfiledowngrade -Fail-)  and (l1 dom l2)  or (t1 == mlsfiledowngrade -Fail-)D

      Possible cause is the source level (s15:c0.c1023) and target level (s0) are different.`

This is my *build.conf *   file
```TYPE = mls
NAME = refpolicy
UNK_PERMS = allow
DIRECT_INITRC = y
MONOLITHIC = n
UBAC = y
CUSTOM_BUILDOPT =
MLS_SENS = 16
MLS_CATS = 1024
MCS_CATS = 1024
QUIET = n
```
Please suggest me what is the problem...

Thanks,

**Comment by rammohanreddy434** [comment]
Got the solution for the above problem .
After adding the `setrans. conf` file in refpolicy directory then problem solved....

Now i',m facing the other problem while in enforcement mode , in
