### ISSUE TITLE
How can I disable some modules to be built

### ISSUE THREAD

**Issue by ratagupt** [SELinuxProject/refpolicy#379]
Earlier there were policy/ modules.conf was there which can be used to prevent a module from being used. Now I don't find this file.

`This file contains a listing of available modules, and how they will be used when building Reference Policy. To prevent a module from  being used, set the module to"off".  For monolithic policies, modules set to "base"	and "module" will be included in the policy.  For modular policies, modules set to "base"will be included in the base module; those set to "module" will becompiled as individual loadable modules.`

**Comment by pebenito** [comment]
You need to run `make conf` and a modules.conf will be generated for you, with all modules listed in it.

**Comment by ratagupt** [comment]
Thanks @pebenito
