### ISSUE TITLE
Add support for container runtimes (podman, docker, etc) (or container-selinux support)

### ISSUE THREAD

**Issue by 0xC0ncord** [SELinuxProject/refpolicy#397]
Container runtime support is currently missing in refpolicy. An issue was opened at container-selinux to bring the possibility to build it against refpolicy, but doing so presents some problems that need reworking. The idea to make container-selinux compatible with refpolicy was the originally proposed solution, but it may instead be wiser to begin work on a container module in refpolicy itself, as to avoid the many incompatibilities or to avoid rules deemed potentially too permissive in refpolicy, etc.

Either way, I am opening this issue to bring visibility on this, as overall support for container runtimes in refpolicy seems to be reaching high demand.

container-selinux issue: https://github.com/containers/container-selinux/issues/113

**Comment by pebenito** [comment]
> it may instead be wiser to begin work on a container module in refpolicy itself, as to avoid the many incompatibilities or to avoid rules deemed potentially too permissive in refpolicy, etc.

I'm open to further comments. I could see going either way.

**Comment by doverride** [comment]
"Build container-selinux with standard refpolicy"

That should be relatively straight-forward to do. Identify the current issues and address them in "container-selinux" where possible and in refpolicy where needed. Should not be too intrustive?

Whether refpolicy should have its own container policy seems to be a different question to me.

**Comment by pebenito** [comment]
Perhaps. But it also influenced by container-selinux and if it works and is considered sufficient.

**Comment by pebenito** [comment]
It would probably be best to discuss on the refpolicy mail list to get broader opinions.
