### ISSUE TITLE
userdom_unpriv_user_template macros is not working 

### ISSUE THREAD

**Issue by serega990306** [SELinuxProject/refpolicy#439]
I installed the latest release version of the Refpolicy from DownloadRelease page. And now I have problems using userdom_unpriv_user_template macros. I made a module:
```
policy_module(userdom, 1.0.0)

userdom_unpriv_user_template(pluff)
```
And `semodule -i userdom.pp` gives errors like:
`Failed to resolve booleanif statement at ...`
`Failed to resolve typeattribute statement at ...`

This happens because refpolicy doesn't declare necessary attributes, types, and booleans. But why is this so? When I used standard selinux this macros worked fine. What am I doing wrong?

**Comment by pebenito** [comment]
I can't reproduce this error. Please provide more details on how you are building this.

**Comment by cgzones** [comment]
I think you have to either manually declare the role beforehand

```
role pluff_r;
userdom_unpriv_user_template(pluff)
```

or define the user via `gen_user(pluff_u, pluff, pluff_r, s0, s0)` in *policy/users*.

**Comment by serega990306** [comment]
I downloaded the latest release from the DownloadRelease page. Extracted files `tar -jxvf refpolicy-2.20180114.tar.bz2 -C /root `. Altered `build.conf` file. And simultaneously executed commands:
```
#make install-src
#cd /etc/selinux/refpolicy/src/policy
#make conf
#make load
```
Then altered `/etc/selinux/config` file to use new policy. And executed:
```
#touch /.autorelabel
#reboot
```
After all this I tried to install a new module:
```
role pluff_r;
userdom_unpriv_user_template(pluff)
```
And I got an error:
```
[root@user-mls userdom]# semodule -i userdom.pp
Failed to resolve booleanif statement at /var/lib/selinux/refpol/tmp/modules/400/userdom/cil:1133
semodule:  Failed!
```

I guess I missed something, but I had used official instruction so I am stuck here.

Also, `gen_user(pluff_u, pluff, pluff_r, s0, s0)` creates user but it doesn't create types, attributes, and booleans like  `userdom_unpriv_user_template` does. May I face any difficulties because of it later?

**Comment by serega990306** [comment]
I have already solved this issue. I didn't install policy headers and this was the problem.
