### ISSUE TITLE
Disabling `kerberos_enabled` boolean breaks `systemd-resolved`

### ISSUE THREAD

**Issue by DemiMarie** [SELinuxProject/refpolicy#440]
`systemd-resolved` isn’t able to start if the `kerberos_enabled` and `nis_enabled` booleans are disabled, as it cannot listen on port 53 on loopback.  Fix coming.

**Comment by DemiMarie** [comment]
Still an issue

**Comment by doverride** [comment]
say's "Fix coming". where is it? any ETA?

**Comment by DemiMarie** [comment]
That’s my own fault @doverride

**Comment by DemiMarie** [comment]
Actually this has already been fixed; it was an old Fedora policy bug.
