### ISSUE TITLE
Unable to get valid context for root

### ISSUE THREAD

**Issue by serega990306** [SELinuxProject/refpolicy#445]
Hello, I have installed refpolicy and now I get this error - `Unable to get valid context for root` on login via ssh. Also, I get the error for other users with other seusers.
How can I fix this?
I cloned the project from git, altered `build.conf` file, and executed these commands:
```
# make install-src
# cd /etc/selinux/refpolicy/src/policy
# make conf
# make load
# touch /.autorelabel
# reboot
```

**Comment by doverride** [comment]
Sergei Petrov ***@***.***> writes:

> Hello, I have installed refpolicy and now I get this error - Unable to get valid context for root
> on login via ssh. Also, I get the error for other users with other seusers.
> How can I fix this?
> I cloned the project from git, altered build.conf file, and executed these commands:
>
> # make install-src
> # cd /etc/selinux/refpolicy/src/policy
> # make conf
> # make load
> # touch /.autorelabel
> # reboot

There is a boolean you can set to make this work I believe. It is called
something like "ssh_priv_login". See if setting that to true helps.


>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift

**Comment by doverride** [comment]
.... or maybe ssh_sysadm_login, not sure but something with ssh and login: `getsebool -a | grep ssh | grep login`

**Comment by serega990306** [comment]
The problem is not that I can not do it at all. I can login via ssh, but after doing so I get :
```
Unable to get valid context for root
Last login: Thu Dec  2 17:02:15 2021 from 10.0.1.124
[root@user-mls ~]# id -Z
system_u:system_r:sysadm_t:s0-s15:c0.c1023
```
And the user does not have the correct selinux context. This happens with all seusers.

I know how to fix this for, at least, root user. This error resolves by altering the files - `/etc/selinux/refpolicy/contexts/default_contexts` and `/etc/selinux/refpolicy/contexts/users/root`.
But this error should not be at all for default roles and users.

This also happens when I create a custom role using this guide: http://selinuxproject.org/page/RefpolicyBasicRoleCreation

**Comment by doverride** [comment]
Hm... dunno

Can you be more specific and explain how exactly you altered` /etc/selinux/refpolicy/contexts/default_contexts` and `/etc/selinux/refpolicy/contexts/users/root`? (ie. before and after?)

**Comment by doverride** [comment]
As for creating custom roles, yes when you create a custom role then you have to address  the context configuration for that role manually, but I agree that this should "just" work for default users.

**Comment by serega990306** [comment]
For `/etc/selinux/refpolicy/contexts/default_contexts` file I removed this line:
 `system_r:init_t:s0		user_r:user_systemd_t:s0 staff_r:staff_systemd_t:s0 sysadm_r:sysadm_systemd_t:s0 unconfined_r:unconfined_t:s0`

For `/etc/selinux/refpolicy/contexts/users/root` file I removed this:
`system_r:init_t:s0		unconfined_r:unconfined_t:s0 sysadm_r:sysadm_systemd_t:s0 staff_r:staff_systemd_t:s0 user_r:user_systemd_t:s0`

And for a custom role, I created the necessary context files. I know that they are legit, because I used them for the standard SELinux MLS policy (not refpolicy) and they worked fine. After setting up refpolicy they do not work either.

**Comment by doverride** [comment]
We're overlooking something ... those init_t entries should not have any effect on the context of the login shell with sshd_t (but you should not use libpam-systemd on MLS systems either).

**Comment by doverride** [comment]
Is the label of the sshd process correct? (system_u:system_r:sshd_t:s0)

**Comment by serega990306** [comment]
How do I check the context label?

**Comment by serega990306** [comment]
Using `ps -axZ | grep ssh` I get:
```
system_u:system_r:init_t:s0-s15:c0.c1023 3819 ? Ss    0:00 sshd: root [priv]
system_u:system_r:init_t:s0-s15:c0.c1023 3824 ? Ss    0:00 sshd: root [priv]
system_u:system_r:init_t:s0-s15:c0.c1023 3826 ? S     0:00 sshd: root@pts/2
system_u:system_r:init_t:s0-s15:c0.c1023 3855 ? S     0:00 sshd: root@notty
```

**Comment by doverride** [comment]
`ps axZ | grep ssh`

**Comment by doverride** [comment]
Looks like you might have a labeling issue?

setenforce 0
restorecon -RvF /
ls -alZ /usr/sbin/sshd
systemctl restart sshd
ps auxZ| grep ssh
setenforce 1

the label type of "sshd" should be sshd_t and not init_t

**Comment by serega990306** [comment]
Same output as before. Also:
```
ls -alZ /usr/sbin/sshd
-rwxr-xr-x. 1 root root system_u:object_r:sshd_exec_t:s0 3934744 мая 23  2019 /usr/sbin/sshd
```

And using `systemctl status sshd` I see:
```
error: ssh_selinux_setup_pty: security_compute_relabel: Invalid argument
sshd[4378]: Accepted password for root from 10.0.1.124 port 55933 ssh2
sshd[4378]: pam_selinux(sshd:session): Security context root:sysadm_r:sysadm_systemd_t:s0-s15:c0.c1023 is not allowed for root:sysadm_r:sysad>
sshd[4378]: pam_selinux(sshd:session): Unable to get valid context for root
sshd[4378]: pam_unix(sshd:session): session opened for user root by (uid=0)
```

**Comment by serega990306** [comment]
Maybe I did something wrong during the installation of the refpolicy? Because I have not seen other issues or questions on this problem.

**Comment by doverride** [comment]
Maybe but MLS is not that widely used.
I would not jump to conslusions and panic though.
I would just determine whether the sshd process runs with type sshd_t first.
If it does not run with type sshd_t then I would try to determine why it is not running with type sshd_t.
the label of the sshd executable file looks correct. So then why is init_t not transitioning to sshd_t then when sshd is started?

**Comment by doverride** [comment]
In the end it is just essential that sshd runs with system_u:system_r:sshd_t and not with system_u:system_r:init_t

**Comment by serega990306** [comment]
Ok, thank you, I will look further in this direction.

**Comment by doverride** [comment]
init_t should just transition to sshd_t on execution of files with type sshd_exec_t. The only thing I can come up with where this would not be happening is when the filesystem is mounted with the 'nosuid' flag.

**Comment by doverride** [comment]
...or when the automatic transition is override by a manual transition

**Comment by serega990306** [comment]
I've solved the problem! My `build.conf` file was wrong. I changed these settings:
```
DIRECT_INITRC = y
SYSTEMD = y
```

**Comment by doverride** [comment]
Sergei Petrov ***@***.***> writes:

> I've solved the problem! My build.conf file was wrong. I changed these settings:
>
> DIRECT_INITRC = y
> SYSTEMD = y

Interesting. I guess when systemd is not enabled there is no transition
from init_t to sshd_t?

Thanks for letting us know the solution!

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift
