### ISSUE TITLE
How to deal with constraint violations

### ISSUE THREAD

**Issue by serega990306** [SELinuxProject/refpolicy#447]
I've created two users:
```
# semanage login -l
tim                  pluff1_u             s1                   *
tom                 pluff0_u             s0                   *

# semanage user -l
pluff0_u        user       s0         s0         myrole_r
pluff1_u        user       s1         s1         myrole_r
```

Then I created and installed a module that allows login via ssh for myrole users. And it works fine for user Tom with s0 level. But doesn't work for Tim with level s1. Using `cat /var/log/audit/audit.log | audit2allow -l` I get a lot of constraint violations, for example^
```
#Constraint rule:
#       mlsconstrain tcp_socket { write setattr relabelfrom connect setopt shutdown } ((l1 eq l2 -Fail-)  or (t1 == mlsnetwriteranged -Fail-)  and (l1 dom l2)  and (l1 domby h2)  or (t1 == mlsnetwritetoclr -Fail-)  and (h1 dom l2)  and (l1 domby l2 -Fail-)  or (t1 == mlsnetwrite -Fail-) ); Constraint DENIED
mlsconstrain tcp_socket { recvfrom } ((l1 eq l2 -Fail-)  or (t1 == mlsnetreadtoclr -Fail-)  and (h1 dom l2)  or (t1 == mlsnetread -Fail-) ); Constraint DENIED

#       Possible cause is the source user (pluff1_u) and target user (system_u) are different.
#       Possible cause is the source role (myrole_r) and target role (system_r) are different.
#       Possible cause is the source level (s1) and target level (s0-s15:c0.c1023) are different.
allow myrole_t sshd_t:tcp_socket { setopt write };
```

Considering that user Tom can log in via ssh, the  cause is the source level (s1).  How can I deal with such constraint violations?

**Comment by doverride** [comment]
My MLS-fu lacks but the feedback from audit2allow is pretty good.

First consider the golden MLS-rule: "no read up and no write down"

Audit2allow tells you there are various conditions where the specified event would be allowed but no conditions were met:

**The event:**
mlsconstrain tcp_socket { write setattr relabelfrom connect setopt shutdown }

**The conditions:**
* (l1 eq l2 -Fail-)
* (t1 == mlsnetwriteranged -Fail-)
* (l1 dom l2)  and (l1 domby h2)  or (t1 == mlsnetwritetoclr -Fail-) 
* (h1 dom l2)  and (l1 domby l2 -Fail-)
* (t1 == mlsnetwrite -Fail-) 

**The event:**
mlsconstrain tcp_socket { recvfrom }

**The conditions:**
* (l1 eq l2 -Fail-)
* (t1 == mlsnetreadtoclr -Fail-) 
* (h1 dom l2)  or (t1 == mlsnetread -Fail-)

I gives you three possible causes but the last one if probably the culprit (MLS):

"Possible cause is the source level (s1) and target level (s0-s15:c0.c1023) are different."

So

* l1 is s1
* h1 is s1
* l2 is s0
* h2 is s15:c0,c1023

You should probably ignore the "t1" conditions, and instead look into solving this puzzle by associating the proper security levels (current and/or clearance) with the user.

Disclaimer: I might be wrong MLS is not  really my thing.

**Comment by doverride** [comment]
I think (but not sure) that the gist is that you are forced to login on s0 with ssh. I guess you are excepted to use a clearance to change your current with something like newrole once you logged in.

**Comment by cgzones** [comment]
Is this on Fedora/RedHat (with their ssh privilege separation patch)? Cause on Debian userdomains do not require access on the sshd TCP socket.
Maybe an exception to the constraint can be added, like:
```
(t2 == mlsnettrustedsocket) and (l1 dom l2) and (h1 domby h2)
```

**Comment by doverride** [comment]
> Is this on Fedora/RedHat (with their ssh privilege separation patch)? Cause on Debian userdomains do not require access on the sshd TCP socket. Maybe an exception to the constraint can be added, like:
> 
> ```
> (t2 == mlsnettrustedsocket) and (l1 dom l2) and (h1 domby h2)
> ```

Semi off-topic

I can confirm that but aside, even though not a critical issue and even though speculating there is this:

```
root@brutus:~# sesearch -A -s user.subj -t openssh.server.subj -c fifo_file
allow user.unpriv.typeattr openssh.server.subj:fifo_file { append getattr ioctl lock read write };
```
and
```
# the "single level" file "write" ops
mlsconstrain { file lnk_file fifo_file dir chr_file blk_file sock_file } { write create setattr relabelfrom append unlink link rename mounton }
	(( l1 eq l2 ) or
	 (( t1 == mlsfilewritetoclr ) and ( h1 dom l2 ) and ( l1 domby l2 )) or
	 (( t2 == mlsfilewriteinrange ) and ( l1 dom l2 ) and ( h1 domby h2 )) or
	 ( t1 == mlsfilewrite ) or
	 ( t2 == mlstrustedobject ));
```
I thin this is triggered by something like:
```
ssh user@host 'command' > file
```
