### ISSUE TITLE
BUG: missing security policy

### ISSUE THREAD

**Issue by pcmoore** [SELinuxProject/refpolicy#455]
*NOTE: I've been debating creating a refpolicy issue for this all day and ultimately decided it couldn't hurt, even though I'm not sure how much of a problem this is in practice.  Regardless of the risk a well defined security policy is never a bad idea.*

There should be a well defined policy for handling serious bugs and security vulnerabilities in the code so that security researchers and others know how to report sensitive issues to the project.  For reference here is the GH documentation on security policies:

* https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

... as well as a simple example of the security policy we use for libseccomp:

* https://github.com/seccomp/libseccomp/security/policy

**Comment by pebenito** [comment]
bump
