### ISSUE TITLE
Make specified domain MLS trusted for translating contexts at all levels

### ISSUE THREAD

**Issue by serega990306** [SELinuxProject/refpolicy#460]
Hello! The problem is that I get an error:

`
audit: type=1401 audit(1640354247.630:3): op=security_validate_transition seresult=denied oldcontext=system_u:object_r:systemd_journal_t:s15:c0.c1023 newcontext=system_u:object_r:systemd_journal_t:s0 taskcontext=system_u:system_r:systemd_tmpfiles_t:s0-s15:c0.c1023 tclass=file
`

To solve the error I could use macros `mls_context_translate_all_levels` but this RefPolicy doesn't have it. Is there any other way to deal with it?

**Comment by pebenito** [comment]
This isn't an error for translating contexts. It's an error for changing the level of the journal file from `s15:c0.c1023` (system high) to `s0` (system low). The file contexts incorrectly have the journal files as system low.
