### ISSUE TITLE
add httpd_rotatelogs_exec_t httpd_logs_t unlink permission

### ISSUE THREAD

**Issue by mhitza** [SELinuxProject/refpolicy#464]
I think it would be helpful to have a `httpd_exec_*_t` that is allowed to unlink `httpd_logs_t`.

Writing out my own logrotation program for apache I was surprised that it could not delete log files, and that I would have to write a specific type enforcement.

Maybe there could be a boolean flag to allow `httpd_rotatelogs_exec_t` to delete files as well?

**Comment by doverride** [comment]
It exists:

https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/services/apache.te#L1332

It is allowed to unlink httpd_log_t files. You should be able to use that. What AVC denials are you seeing?

**Comment by doverride** [comment]
Might be labeling issue? The policy expects this program to be installed to `/usr/s?bin`

https://github.com/SELinuxProject/refpolicy/blob/master/policy/modules/services/apache.fc#L52

**Comment by mhitza** [comment]
You're right. I had a script that I labeled with httpd_rotatelogs_exec_t, but via an interpreter thus it inherited a httpd_t type instead of httpd_rotatelogs_t.

PEBKAC
