### ISSUE TITLE
Questions about contianer module

### ISSUE THREAD

**Issue by wdsun1008** [SELinuxProject/refpolicy#493]
I'm trying to use Udica on Ubuntu 20.04, it is based on fedora selinux policy and [container-selinux](https://github.com/containers/container-selinux).     
@0xC0ncord was doing a great job on this, I just have a few questions:     

Is container-selinux policy already included in the refpolicy container module? or refpolicy container module just make refpolicy compatible to container-selinux? I notice that refpolicy doesn’t have some types like container_runtime_exec_t.     

Thanks

**Comment by pebenito** [comment]
Refpolicy does not include Fedora's container-selinux; it has its own implementation, as container-selinux itself cannot be loaded on refpolicy, and I disagree with some of the implementation in container-selinux. My hope is for refpolicy to have as much compatibility as possible.

**Comment by wdsun1008** [comment]
> Refpolicy does not include Fedora's container-selinux; it has its own implementation, as container-selinux itself cannot be loaded on refpolicy, and I disagree with some of the implementation in container-selinux. My hope is for refpolicy to have as much compatibility as possible.

Thanks very much!
