### ISSUE TITLE
Fail to build policy fapolicyd if DIRECT_INITRC=y

### ISSUE THREAD

**Issue by yizhao1** [SELinuxProject/refpolicy#550]
I got the following build error when set DIRECT_INITRC=y

| Conflicting type rules (scontext=sysadm_t tcontext=fagenrules_exec_t tclass=process result=fagenrules_t), existing=initrc_t
| Expanded from type rule (scontext=sysadm_t tcontext=fagenrules_exec_t tclass=process result=fagenrules_t)
| Binary policy creation failed at /buildarea4/yzhao1/yocto/build-test/tmp/work/qemux86_64-poky-linux/refpolicy-standard/2.20220520+gitAUTOINC+20090ad09
8-r0/image/var/lib/selinux/standard/tmp/modules/100/sysadm/cil:11506
| Failed to generate binary

The error is caused by the following line  in fapolicyd.te:
init_script_domain(fagenrules_t, fagenrules_exec_t)

@dsugar100 Would you please take a look at this ? Thanks.

**Comment by dsugar100** [comment]
Interesting, it looks like both DIRECT_INITRC and MONOLITHIC need to be set to 'y' to see a problem.  I don't see an issue if either one is 'n'

**Comment by dsugar100** [comment]
I am going to push in a change - is there a way to attach a commit to this issue?

**Comment by dsugar100** [comment]
This should now be resolved.
