### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by freedom1b2830** [SELinuxProject/refpolicy#616]
1. How to allow all domains to ``append`` to a file ``seclog:file`` ?
```sh
allow ? seclog:file append;
```
2. How to allow torrent ``client_t`` to connect to all 65535
tcp/udp ports ?

**Comment by 0xC0ncord** [comment]
> 1. How to allow all domains to `append` to a file `seclog:file` ?
> 
> ```shell
> allow ? seclog:file append;
> ```
> 

You can use the `domain` attribute for this, e.g:
```
allow domain seclog:file append;
```

> 2. How to allow torrent `client_t` to connect to all 65535
>    tcp/udp ports ?

This should do it, but I'm not 100% sure if it's too coarse or not:
```
corenet_tcp_connect_all_ports(client_t)
allow client_t self:udp_socket create_socket_perms;
corenet_udp_bind_generic_node(client_t)
corenet_udp_sendrecv_generic_if(client_t)
corenet_udp_sendrecv_generic_node(client_t)
```
