### ISSUE TITLE
Modifications to allow minimal initrd policy only

### ISSUE THREAD

**Issue by iam-TJ** [SELinuxProject/refpolicy#814]
I hit some build tooling issues whilst developing a bare-minimum policy for a bug-test virtual machine that only loads kernel and an extremely limited initrd.img that only contains `busybox`,  simple `/init` script, and the required SELinux tooling to load a monolithic policy, relabel, and enable then re-exec `/init`  due to assumptions that some modules would always be present that are not.
This simple change solves it and doesn't appear to cause a regression otherwise. Comments welcome:
```
diff --git a/Rules.monolithic b/Rules.monolithic
index d6e20a371..1fd0db1c2 100644
--- a/Rules.monolithic
+++ b/Rules.monolithic
@@ -207,8 +207,8 @@ enableaudit: $(policy_conf)
 #
 $(fc): $(tmpdir)/$(notdir $(fc)).tmp
 $(verbose) $(fcsort) $< $@
-       $(verbose) $(GREP) -e HOME -e ROLE -e USER $@ > $(homedir_template)
-       $(verbose) $(SED) -i -e /HOME/d -e /ROLE/d -e /USER/d $@
+       $(verbose) $(GREP) -e HOME -e ROLE -e USER $@ > $(homedir_template) || touch $(homedir_template)
+       $(verbose) $(SED) -i -e /HOME/d -e /ROLE/d -e /USER/d $@ || true
 
 $(tmpdir)/$(notdir $(fc)).tmp: $(m4support) $(tmpdir)/generated_definitions.conf $(all_fc_files)
 ifeq ($(all_fc_files),)
```

**Comment by pebenito** [comment]
To propose a change, please submit a pull request. We can look at the artifacts of the github actions and compare output.
