### ISSUE TITLE
latest release 2.20190609 missing could not recognize sctp

### ISSUE THREAD

**Issue by wenhuizhang** [SELinuxProject/refpolicy#85]
```
cat tmp/pre_te_files.conf tmp/all_attrs_types.conf tmp/global_bools.conf tmp/only_te_rules.conf tmp/all_post.conf > base.conf
Compiling refpolicy base module
/usr/bin/checkmodule -U deny base.conf -o tmp/base.mod
/usr/bin/checkmodule:  loading policy configuration from base.conf
policy/modules/kernel/ubac.te:2490:ERROR 'unrecognized protocol sctp' at token 'portcon' on line 28914:
portcon sctp 512-1023 system_u:object_r:hi_reserved_port_t
portcon sctp 1024-65535 system_u:object_r:unreserved_port_t
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
Rules.modular:102: recipe for target 'tmp/base.mod' failed
make: *** [tmp/base.mod] Error 1
```

```
wenhui@wenhui:~/Downloads$ uname -a
Linux wenhui 4.18.0 #1 SMP Sun Aug 25 22:09:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by doverride** [comment]
On Mon, Sep 02, 2019 at 12:02:26PM -0700, Wenhui Zhang wrote:
> ```
> cat tmp/pre_te_files.conf tmp/all_attrs_types.conf tmp/global_bools.conf tmp/only_te_rules.conf tmp/all_post.conf > base.conf
> Compiling refpolicy base module
> /usr/bin/checkmodule -U deny base.conf -o tmp/base.mod
> /usr/bin/checkmodule:  loading policy configuration from base.conf
> policy/modules/kernel/ubac.te:2490:ERROR 'unrecognized protocol sctp' at token 'portcon' on line 28914:
> portcon sctp 512-1023 system_u:object_r:hi_reserved_port_t
> portcon sctp 1024-65535 system_u:object_r:unreserved_port_t
> /usr/bin/checkmodule:  error(s) encountered while parsing configuration
> Rules.modular:102: recipe for target 'tmp/base.mod' failed
> make: *** [tmp/base.mod] Error 1
> ```
> 
> 
> ```
> wenhui@wenhui:~/Downloads$ uname -a
> Linux wenhui 4.18.0 #1 SMP Sun Aug 25 22:09:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
> 
> ```
> 

What version of SELinux user space do you use?

> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/85

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wenhuizhang** [comment]
> On Mon, Sep 02, 2019 at 12:02:26PM -0700, Wenhui Zhang wrote: ``` cat tmp/pre_te_files.conf tmp/all_attrs_types.conf tmp/global_bools.conf tmp/only_te_rules.conf tmp/all_post.conf > base.conf Compiling refpolicy base module /usr/bin/checkmodule -U deny base.conf -o tmp/base.mod /usr/bin/checkmodule: loading policy configuration from base.conf policy/modules/kernel/ubac.te:2490:ERROR 'unrecognized protocol sctp' at token 'portcon' on line 28914: portcon sctp 512-1023 system_u:object_r:hi_reserved_port_t portcon sctp 1024-65535 system_u:object_r:unreserved_port_t /usr/bin/checkmodule: error(s) encountered while parsing configuration Rules.modular:102: recipe for target 'tmp/base.mod' failed make: *** [tmp/base.mod] Error 1 ``` ``` ***@***.***:~/Downloads$ uname -a Linux wenhui 4.18.0 #1 SMP Sun Aug 25 22:09:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux ```
> What version of SELinux user space do you use?
> […](#)
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #85
> -- Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02 https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02 Dominick Grift

**### 2.20190609**

**Comment by doverride** [comment]
On Mon, Sep 02, 2019 at 12:07:55PM -0700, Wenhui Zhang wrote:
> > On Mon, Sep 02, 2019 at 12:02:26PM -0700, Wenhui Zhang wrote: ``` cat tmp/pre_te_files.conf tmp/all_attrs_types.conf tmp/global_bools.conf tmp/only_te_rules.conf tmp/all_post.conf > base.conf Compiling refpolicy base module /usr/bin/checkmodule -U deny base.conf -o tmp/base.mod /usr/bin/checkmodule: loading policy configuration from base.conf policy/modules/kernel/ubac.te:2490:ERROR 'unrecognized protocol sctp' at token 'portcon' on line 28914: portcon sctp 512-1023 system_u:object_r:hi_reserved_port_t portcon sctp 1024-65535 system_u:object_r:unreserved_port_t /usr/bin/checkmodule: error(s) encountered while parsing configuration Rules.modular:102: recipe for target 'tmp/base.mod' failed make: *** [tmp/base.mod] Error 1 ``` ``` ***@***.***:~/Downloads$ uname -a Linux wenhui 4.18.0 #1 SMP Sun Aug 25 22:09:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux ```
> > What version of SELinux user space do you use?
> > […](#)
> > -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #85
> > -- Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02 https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02 Dominick Grift
> 
> **### 2.20190609**

That's refpolicy version. I am wondering about the version of the SELinux user space (libsepol/libselinux etc)

> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/SELinuxProject/refpolicy/issues/85#issuecomment-527226292

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by doverride** [comment]
On Mon, Sep 02, 2019 at 09:06:23PM +0200, Dominick Grift wrote:
> On Mon, Sep 02, 2019 at 12:02:26PM -0700, Wenhui Zhang wrote:
> > ```
> > cat tmp/pre_te_files.conf tmp/all_attrs_types.conf tmp/global_bools.conf tmp/only_te_rules.conf tmp/all_post.conf > base.conf
> > Compiling refpolicy base module
> > /usr/bin/checkmodule -U deny base.conf -o tmp/base.mod
> > /usr/bin/checkmodule:  loading policy configuration from base.conf
> > policy/modules/kernel/ubac.te:2490:ERROR 'unrecognized protocol sctp' at token 'portcon' on line 28914:
> > portcon sctp 512-1023 system_u:object_r:hi_reserved_port_t
> > portcon sctp 1024-65535 system_u:object_r:unreserved_port_t
> > /usr/bin/checkmodule:  error(s) encountered while parsing configuration
> > Rules.modular:102: recipe for target 'tmp/base.mod' failed
> > make: *** [tmp/base.mod] Error 1
> > ```
> > 
> > 
> > ```
> > wenhui@wenhui:~/Downloads$ uname -a
> > Linux wenhui 4.18.0 #1 SMP Sun Aug 25 22:09:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
> > 
> > ```
> > 
> 

We should probably add more clarity about the minimum requirements: Linux v4.16 + SELinux v2.8

> 
> > 
> > 
> > -- 
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/SELinuxProject/refpolicy/issues/85
> 
> -- 
> Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
> https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
> Dominick Grift



-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by wenhuizhang** [comment]
> On Mon, Sep 02, 2019 at 09:06:23PM +0200, Dominick Grift wrote: On Mon, Sep 02, 2019 at 12:02:26PM -0700, Wenhui Zhang wrote: > ``` > cat tmp/pre_te_files.conf tmp/all_attrs_types.conf tmp/global_bools.conf tmp/only_te_rules.conf tmp/all_post.conf > base.conf > Compiling refpolicy base module > /usr/bin/checkmodule -U deny base.conf -o tmp/base.mod > /usr/bin/checkmodule: loading policy configuration from base.conf > policy/modules/kernel/ubac.te:2490:ERROR 'unrecognized protocol sctp' at token 'portcon' on line 28914: > portcon sctp 512-1023 system_u:object_r:hi_reserved_port_t > portcon sctp 1024-65535 system_u:object_r:unreserved_port_t > /usr/bin/checkmodule: error(s) encountered while parsing configuration > Rules.modular:102: recipe for target 'tmp/base.mod' failed > make: *** [tmp/base.mod] Error 1 > ``` > > > ``` > ***@***.***:~/Downloads$ uname -a > Linux wenhui 4.18.0 #1 SMP Sun Aug 25 22:09:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux > > ``` >
> We should probably add more clarity about the minimum requirements: Linux v4.16 + SELinux v2.8
> […](#)
> > > > -- > You are receiving this because you are subscribed to this thread. > Reply to this email directly or view it on GitHub: > #85 -- Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02 https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02 Dominick Grift
> -- Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8 02D5 3B6C 5F1D 2C7B 6B02 https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02 Dominick Grift

Oh, that makes sense, I am using libselinux1 is already the newest version (2.7-2build2). Thanks!
I will update it then.
Thanks Dominick
